### ISSUE TITLE
Releasing via Plugin Installer

### ISSUE THREAD

**Issue by jsiegle** [mich11/multi-band-integrator#3]
Hello! The Open Ephys development team would like to make this plugin available to the community via the GUI's Plugin Installer.

Before we do that, we have a few questions:

* Is the code on GitHub up to date?
* Are there any particular features that need improvement? We are happy to put some effort in to make the plugin as general-purpose as possible
* Is there additional documentation available beside what's in the README file? We will be adding a page dedicated to this plugin on the GUI's new docs site.
* Is there a sample dataset containing absence-like seizures you've been using for testing/benchmarking?

Thanks!

**Comment by mich11** [comment]
Hey!  I'm so excited that y'all are working to make 3rd party plugins easier to install. I'm about to be mostly offline for a couple of weeks during the holidays, but I'm planning to work on this in early January. To answer your questions:

- The code is up to date.  We haven't tried installing the plugin with the latest version of Open Ephys, but my labmates have gotten it working with version 0.4.5.0. 
- Additional features: It would be useful for users to be able to specify the channels on which to output the intermediate weighted frequency bands and final rolling window regression. 
- The readme is _not_ up to date, and the install process has changed dramatically since I originally wrote the plugin. Sorry about that. This will be my top priority to update. This plugin is especially annoying to install because it uses part of the boost library to perform the rolling average. If you know of an easier way to do a rolling average, I would love to change it. 
- I can put together a sample EEG dataset saved in the open-ephys format.  I didn't try to use the plugin with pre-recorded data in open ephys. Instead, I got my initial parameters from pre-recorded data in Matlab and then tested/tuned it during live recordings, as the seizures in our model are pretty frequent. 

Let me know if you have more questions!

**Comment by jsiegle** [comment]
We actually already have it working with the latest version of the GUI [in our fork](https://github.com/open-ephys-plugins/multi-band-integrator). We re-implemented the rolling average without boost, so linking to that library is no longer necessary.

Being able to specify the output channels is a good idea, we can easily implement that.

So, the most helpful thing on your end would be to send some sample data (and the parameters you used for seizure detection, unless those are already the defaults). It's fine to wait until next year for this...we likely won't do the official release until late Jan.

**Comment by mich11** [comment]
Awesome! I'll definitely get you some seizure data and detection parameters in early Jan.

**Comment by jsiegle** [comment]
Hi there! Have you had a chance to look for the sample data yet? We're almost ready to release the plugin, but would like to confirm that our fork is working as expected.

Also, are you available for a brief video call in the next week or so? You can email josh@open-ephys.org to schedule.

**Comment by mich11** [comment]
Hi!

I'll get you that sample data this week.  

And yes! I'll follow up shortly to schedule a call.

**Comment by mich11** [comment]
I've added a small data set of EEG data and seizures detected with post-hoc analysis to benchmark the plugin. Let me know if you have any questions.

**Comment by jsiegle** [comment]
Thanks for the data! I converted one of the files to binary format to test the plugin, and it seems to be working great!

The documentation page is here: https://open-ephys.github.io/gui-docs/User-Manual/Plugins/Multiband-Integrator.html

Please take a look and let me know if you have any feedback!

**Comment by mich11** [comment]
The documentation looks great! I updated the readme here to redirect to to you all for the latest version.
